title: Engineers for Exploration - FishSense
services:
  - title: Temporal
    description: Workflow Orchestration
    link: /temporal
    icon:
      name: simple-icons:temporal
      wrap: true
    status:
      enabled: true