x-superset-image: &superset-image apachesuperset.docker.scarf.sh/apache/superset:5.0.0
x-superset-volumes:
  &superset-volumes # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./superset_volumes/docker:/app/docker
  - ./superset_volumes/home:/app/superset_home

services:
  superset:
    container_name: fishsense_superset
    env_file:
      - path: ./superset_volumes/docker/.env # default
        required: true
      - path: ./.secrets/superset-env # optional override
        required: false
    image: *superset-image
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    restart: on-failure:15
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.superset.rule=Host(`analytics.fishsense.e4e.ucsd.edu`)"
      - "traefik.http.routers.superset.entrypoints=websecure"
      - "traefik.http.routers.superset.tls.certresolver=letsencrypt"
    networks:
      - traefik_proxy
      - default
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes: *superset-volumes

  superset-init:
    image: *superset-image
    container_name: superset_init
    command: ["/app/docker/docker-init.sh"]
    env_file:
      - path: ./superset_volumes/docker/.env # default
        required: true
      - path: ./.secrets/superset-env # optional override
        required: false
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true

  superset-worker:
    image: *superset-image
    container_name: superset_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file:
      - path: ./superset_volumes/docker/.env # default
        required: true
      - path: ./.secrets/superset-env # optional override
        required: false
    restart: on-failure:15
    depends_on:
      superset-init:
        condition: service_completed_successfully
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME",
        ]

  superset-worker-beat:
    image: *superset-image
    container_name: superset_worker_beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    env_file:
      - path: ./superset_volumes/docker/.env # default
        required: true
      - path: ./.secrets/superset-env # optional override
        required: false
    restart: on-failure:15
    depends_on:
      superset-init:
        condition: service_completed_successfully
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true

  redis:
    image: redis:7
    container_name: superset_cache
    restart: on-failure:15
    volumes:
      - ./redis_volumes/data:/data