CREATE DATABASE temporal_db;

CREATE ROLE temporal WITH
    LOGIN
    ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:dd4iNdjdRRX2m+ZHG1IG0w==$QNM8EGQr+bgn4JwScM+7c2YjyuYH0iLJDYk6/YAvyeM=:whxgK2XtZmRHjYygo0l4yMf3BgB0oaISDSRsTwcSGcE=';
GRANT ALL PRIVILEGES ON DATABASE temporal_db TO temporal;
\c temporal_db postgres
GRANT ALL ON SCHEMA public TO temporal;